server.port: 8080
spring.application.name: gateway-service
eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: author-service
            uri: http://localhost:8001
            #uri: lb://author-service
            predicates:
              - Path=/author/**
            filters:
              - PrefixPath=/api/v1
          - id: book-service
            uri: http://localhost:8002
            predicates:
              - Path=/book/**
            filters:
              - PrefixPath=/api/v1

