server.port: 8080
spring.application.name: gateway-service
eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: author-service
            uri: http://localhost:8001
            #uri: lb://author-service
            predicates:
              - Path=/author/**
              - Before=2024-01-17T00:00:00.000-05:00

          - id: book-service
            uri: http://localhost:8002
            predicates:
              - Path=/book/**
              - After=2024-01-16T00:00:00.000-05:00
              - Header=X-Custom-Header, custom-value
            filters:
              - PrefixPath=/api/v1

